"""add random_key -> BookModel

Revision ID: c3dd44bbd6cd
Revises: 097d44a114dd
Create Date: 2026-06-13 14:07:02.201909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3dd44bbd6cd'
down_revision: Union[str, None] = '097d44a114dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('random_key', sa.BigInteger(), server_default=sa.text('(floor(random() * 9223372036854775807))::bigint'), nullable=False))
    op.create_index('ix_books_available_random_key', 'books', ['is_available', 'random_key'], unique=False)
    op.create_index('ix_books_random_key', 'books', ['random_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_random_key', table_name='books')
    op.drop_index('ix_books_available_random_key', table_name='books')
    op.drop_column('books', 'random_key')
    # ### end Alembic commands ###
