"""init

Revision ID: 2c3a322990d4
Revises: 
Create Date: 2026-07-10 15:01:13.233253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c3a322990d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authors')),
    sa.UniqueConstraint('name', name=op.f('uq_authors_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_authors_slug'))
    )
    op.create_table('book_categories',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_book_categories_slug'))
    )
    op.create_table('countries',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('country', name=op.f('uq_countries_country')),
    sa.UniqueConstraint('slug', name=op.f('uq_countries_slug'))
    )
    op.create_table('paper_types',
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_types')),
    sa.UniqueConstraint('type_name', name=op.f('uq_paper_types_type_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', postgresql.ENUM('google', 'github', name='oauth_provider_enum'), nullable=True),
    sa.Column('oauth_id', sa.String(), nullable=True),
    sa.Column('role', postgresql.ENUM('user', 'manager', 'admin', name='client_role_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=True)
    op.create_index(op.f('ix_users_oauth_provider'), 'users', ['oauth_provider'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('addresses',
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('books',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pages', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('img', sa.String(length=255), nullable=True),
    sa.Column('discount_percent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('issue_year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('total_ratings', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sum_ratings', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_sales', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('random_key', sa.BigInteger(), server_default=sa.text('(floor(random() * 9223372036854775807))::bigint'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('paper_type_id', sa.Integer(), nullable=True),
    sa.Column('made_in_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='check_discount_range'),
    sa.CheckConstraint('pages >= 0', name='check_pages_positive'),
    sa.CheckConstraint('price >= 0', name='check_price_positive'),
    sa.CheckConstraint('quantity >= 0', name='check_quantity_positive'),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name=op.f('fk_books_author_id_authors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['book_categories.id'], name=op.f('fk_books_category_id_book_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['made_in_id'], ['countries.id'], name=op.f('fk_books_made_in_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_type_id'], ['paper_types.id'], name=op.f('fk_books_paper_type_id_paper_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('slug', name=op.f('uq_books_slug'))
    )
    op.create_index('ix_books_available_random_key', 'books', ['is_available', 'random_key'], unique=False)
    op.create_index('ix_books_random_key', 'books', ['random_key'], unique=False)
    op.create_table('carts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('user_id', name=op.f('uq_carts_user_id'))
    )
    op.create_table('chats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', postgresql.ENUM('operator_request', 'complex_case', 'profanity', name='escalationreason'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('(is_closed = false) OR (closed_at IS NOT NULL)', name='closed_at_required_if_closed'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_chats_manager_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_index('ix_chat_escalation_queue', 'chats', ['is_closed', 'escalation_reason', 'manager_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_chats_is_closed'), 'chats', ['is_closed'], unique=False)
    op.create_index(op.f('ix_chats_last_message_at'), 'chats', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_chats_manager_id'), 'chats', ['manager_id'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index('unique_active_chat_per_user', 'chats', ['user_id'], unique=True, postgresql_where=sa.text('is_closed IS false'))
    op.create_table('book_popularity_stats',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('sales', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wishlist_adds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('popularity_score', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_popularity_stats_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'stat_date', name=op.f('pk_book_popularity_stats'))
    )
    op.create_index(op.f('ix_book_popularity_stats_popularity_score'), 'book_popularity_stats', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_book_popularity_stats_stat_date'), 'book_popularity_stats', ['stat_date'], unique=False)
    op.create_table('cart_items',
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_cart_items_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'book_id', name='uq_cart_book')
    )
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender', postgresql.ENUM('user', 'bot', 'manager', name='messagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.create_table('orders',
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'shipped', 'delivered', 'canceled', name='order_status_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_orders_address_id_addresses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_review_rating_range'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reviews_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('user_events',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('event_type', postgresql.ENUM('view', 'search', 'wishlist_add', 'wishlist_remove', 'cart_add', 'cart_remove', 'purchase', 'rating', 'share', 'preview', name='user_event_enum'), nullable=False),
    sa.Column('metada', sa.JSON(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_user_events_book_id_books'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_events'))
    )
    op.create_index('ix_user_events_created', 'user_events', ['created_at'], unique=False)
    op.create_index('ix_user_events_user_book', 'user_events', ['user_id', 'book_id'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_index('ix_user_events_user_type', 'user_events', ['user_id', 'event_type'], unique=False)
    op.create_table('wishlists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_wishlists_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name=op.f('pk_wishlists'))
    )
    op.create_table('order_items',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_order_items_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_book_id'), 'order_items', ['book_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', postgresql.ENUM('card', 'paypal', 'apple_pay', 'other', name='payment_method_enum'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', name='payment_status_enum'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('order_id', name=op.f('uq_payments_order_id'))
    )
    op.create_index(op.f('ix_payments_payment_intent_id'), 'payments', ['payment_intent_id'], unique=True)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_intent_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_book_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('wishlists')
    op.drop_index('ix_user_events_user_type', table_name='user_events')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index('ix_user_events_user_book', table_name='user_events')
    op.drop_index('ix_user_events_created', table_name='user_events')
    op.drop_table('user_events')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_book_popularity_stats_stat_date'), table_name='book_popularity_stats')
    op.drop_index(op.f('ix_book_popularity_stats_popularity_score'), table_name='book_popularity_stats')
    op.drop_table('book_popularity_stats')
    op.drop_index('unique_active_chat_per_user', table_name='chats', postgresql_where=sa.text('is_closed IS false'))
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_manager_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_message_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_is_closed'), table_name='chats')
    op.drop_index('ix_chat_escalation_queue', table_name='chats')
    op.drop_table('chats')
    op.drop_table('carts')
    op.drop_index('ix_books_random_key', table_name='books')
    op.drop_index('ix_books_available_random_key', table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_provider'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('paper_types')
    op.drop_table('countries')
    op.drop_table('book_categories')
    op.drop_table('authors')
    # ### end Alembic commands ###
