FROM rabbitmq:4.2-management

RUN apt-get update && apt-get install -y --no-install-recommends wget \
    && wget -O /plugins/rabbitmq_delayed_message_exchange.ez \
       https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.2.0/rabbitmq_delayed_message_exchange-4.2.0.ez \
    && apt-get remove -y wget && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange